name: Notify Slack with PR List

on:
  # Trigger when a PR is created, edited, or synchronized
  pull_request:
    types: [opened, synchronize, edited, labeled, unlabeled]
  schedule:
    - cron: '0 9 * * 1-5'  # Run at 9 AM UTC on weekdays

jobs:
  notify_slack:
    runs-on: ubuntu-latest

    steps:
      - name: Notify Slack about PRs
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const tag = 'contact-center';
            const folderPath = '.github';

            // Fetch all open pull requests
            const { data: pullRequests } = await github.rest.pulls.list({
              owner,
              repo,
              state: 'open'
            });

            const filteredPRs = await Promise.all(pullRequests.map(async pr => {
              // Check if PR has the specified label
              const hasLabel = pr.labels.some(label => label.name === tag);
              
              // Check if PR has changes in the specified folder
              const { data: files } = await github.rest.pulls.listFiles({
                owner,
                repo,
                pull_number: pr.number
              });
              const hasChangesInFolder = files.some(file => file.filename.includes(folderPath));
              
              return (hasLabel || hasChangesInFolder) ? pr : null;
            }));

            const relevantPRs = filteredPRs.filter(pr => pr !== null);

            let message;
            if (relevantPRs.length === 0) {
              message = `*Open Pull Requests (${tag} or ${folderPath}):*\nThere are currently no open pull requests with the '${tag}' label or changes in '${folderPath}'.`;
            } else {
              const prList = relevantPRs.map(pr => {
                const labels = pr.labels.map(label => label.name).join(', ');
                return `- <${pr.html_url}|PR #${pr.number}: ${pr.title}> by ${pr.user.login} [${labels}]`;
              }).join('\n');
              message = `*Open Pull Requests (${tag} or ${folderPath}):*\n${prList}`;
            }

            // Send the message to Slack via the webhook
            const slackWebhookUrl = process.env.SLACK_WEBHOOK_URL;

            try {
              const response = await fetch(slackWebhookUrl, {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ text: message })
              });

              if (!response.ok) {
                throw new Error(`Slack Webhook request failed with status ${response.status}`);
              }

              console.log('PR status sent to Slack.');
            } catch (error) {
              console.error('Failed to send PR status to Slack:', error.message);
            }

        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}