name: Notify Slack with PR List

on:
  # Trigger when a PR is created, edited, or synchronized
  pull_request:
    types: [opened, synchronize, edited, labeled, unlabeled]
  schedule:
    - cron: '0 9 * * 1-5'  # Run at 9 AM UTC on weekdays

jobs:
  notify_slack:
    runs-on: ubuntu-latest

    steps:
      - name: Notify Slack about PRs
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const tag = 'contact-center';

            // Fetch all open pull requests
            const { data: pullRequests } = await github.rest.pulls.list({
              owner,
              repo,
              state: 'open'
            });

            const filteredPRs = pullRequests.filter(pr => 
              pr.labels.map(label => label.name).includes(tag)
            );

            let message;
            if (filteredPRs.length === 0) {
              message = `*Open Pull Requests (${tag}):*\nThere are currently no open pull requests with the '${tag}' label.`;
            } else {
              const prList = filteredPRs.map(pr => `- <${pr.html_url}|PR #${pr.number}: ${pr.title}> by ${pr.user.login}`).join('\n');
              message = `*Open Pull Requests (${tag}):*\n${prList}`;
            }

            // Send the message to Slack via the webhook
            const slackWebhookUrl = process.env.SLACK_WEBHOOK_URL;

            try {
              const response = await fetch(slackWebhookUrl, {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ text: message })
              });

              if (!response.ok) {
                throw new Error(`Slack Webhook request failed with status ${response.status}`);
              }

              console.log('PR status sent to Slack.');
            } catch (error) {
              console.error('Failed to send PR status to Slack:', error.message);
            }

        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}